source: .
collections_config:
  pages:
    path: .
    glob:
      - '*.html'
    icon: notes
    url: /[path]
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
output_path: .
